name: flutter_demo_ssuriset
description: "A new Flutter project."
publish_to: 'none' # Prevents accidental publishing

version: 1.0.0+1

environment:
  # Dart SDK constraint
  sdk: ">=3.7.2 <4.0.0"
  # Flutter SDK constraint (optional but recommended)
  flutter: ">=3.22.0"

dependencies:
  # Flutter framework
  flutter:
    sdk: flutter

  # iOS-style icons
  cupertino_icons: ^1.0.8

  # Firebase core SDK
  firebase_core: ^3.13.0

  # Firebase Authentication
  firebase_auth: ^5.5.3

  # Cloud Firestore
  cloud_firestore: ^5.6.7

  # State management
  provider: ^6.1.4

dev_dependencies:
  # Flutter’s test framework
  flutter_test:
    sdk: flutter

  # Lint rules
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true