name: Deploy to Firebase Hosting on PR
on: pull_request
permissions:
  checks: write
  contents: read
  pull-requests: write

jobs:
  build_and_preview:
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest

    steps:

      # 1) Checkout code
      - uses: actions/checkout@v4

      # 2) Cache Flutter SDK
      - name: Cache Flutter SDK
        uses: actions/cache@v3
        with:
          path: /opt/hostedtoolcache/flutter
          key: ${{ runner.os }}-flutter-stable
          restore-keys: |
            ${{ runner.os }}-flutter-

      # 3) Cache Dart/Flutter packages
      - name: Cache pub cache
        uses: actions/cache@v3
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-cache-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-cache-

      # 4) Install Flutter SDK (latest stable)
      - name: Install Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      # 5) Install dependencies
      - name: Pub get
        run: flutter pub get
        env:
          PUB_CACHE: ~/.pub-cache

      # 6) Build Flutter web
      - name: Build Web
        run: flutter build web --release

      # 7) Deploy to Firebase Hosting (preview)
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_SSURISET_FLUTTER_DEMO }}
          projectId: ssuriset-flutter-demo